controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionAdminLogin()
    {
        
        $this->layout = 'login';
        if (!Yii::$app->user->isGuest) {
            return $this->redirect('admin/contact');
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('admin/contact');
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(['admin-login']);
    }

}

backend/views/layouts/_formBtns.php
<?php
use yii\helpers\Html;
?>

<div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
        <div class="pull-md-left">
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-primary m-r-10', 'name' => '']) ?>
            <?= Html::submitButton(Yii::t('app', 'Apply'), ['class' => 'btn btn-success m-r-10', 'name' => 'apply']) ?>
            <?= Html::submitButton(Yii::t('app', 'Create new'), ['class' => 'btn btn-default m-r-10', 'name' => 'new']) ?>
        </div>
        <div class="pull-md-right">
            <?= Html::a(Yii::t('app', 'Cancel'), ['index'], ['class' => 'btn btn-warning']) ?>
		</div>
	</div>
</div>

backend/views/layouts/_header.php
<?php

use yii\bootstrap\Nav;
use yii\helpers\Html;

$controllerId = Yii::$app->controller->id;
$method = Yii::$app->controller->action->id;

?>

<div class="site-header">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <a class="collapse-button navbar-item pull-left hidden-lg hidden-md"><i class="ti-menu"></i></a>
            <a class="navbar-brand" href="/admin-login"><span
                        class="hidden-xs"><?php echo Yii::$app->name; ?></span></a>
            <div class="visible-lg visible-md">
                <?php
                echo Nav::widget([
                    'options' => ['class' => 'nav navbar-nav'],
                    'items' => [
                        [
                            'label' => Yii::t('app', 'Contacts'), 
                            'url' => '/admin/contact', 
                            'active' => ($controllerId == 'contact')
                        ],
                        [
                            'label' => 'Модули',
                            'items' => [
                                ['label' => Yii::t('app', 'Slides'), 'url' => '/admin/slide', 'active' => ($controllerId == 'slide')],
                                ['label' => Yii::t('app', 'Advantage'), 'url' => '/admin/advantage', 'active' => ($controllerId == 'advantage')],
                                ['label' => Yii::t('app', 'Services'), 'url' => '/admin/service', 'active' => ($controllerId == 'service')],
                                ['label' => 'Социальные сети', 'url' => '/admin/social', 'active' => ($controllerId == 'social')]
                            ],
                            'active' => in_array($controllerId, [
                                'slide', 'advantage', 'service', 'social',
                            ])
                        ],
						['label' => Yii::t('app', 'Pages'), 'url' => '/admin/page', 'active' => ($controllerId == 'page')],
                        ['label' => Yii::t('app', 'Menu'), 'url' => '/admin/menu', 'active' => ($controllerId == 'menu')],
                    ],
                ]);
                ?>
            </div>
            <?php

            echo Nav::widget([
                'options' => ['class' => 'navbar-right nav navbar-nav'],
                'encodeLabels' => false,

                'items' => [
                    [
                        'label' => '<i class="ti-settings"></i>',
                        'active' => in_array($controllerId, ['settings', 'redirect', 'user-log', 'log']),
                        'items' => [
                            [
                                'label' => Yii::t('app', 'Settings'),
                                'url' => '/admin/settings',
                                'active' => ($controllerId == 'settings' && $method == 'index'),
                            ],
                            [
                                'label' => Yii::t('app', 'Redirects'),
                                'url' => '/admin/redirect',
                                'active' => ($controllerId == 'redirect'),
                            ],
                            '<li class="divider"></li>',
                            [
                                'label' => Yii::t('app', 'Logs'),
                                'url' => '/admin/log',
                                'active' => ($controllerId == 'log'),
                            ],
                        ]
                    ],
                    [
                        'label' => '<i class="ti-new-window"></i>',
                        'url' => Yii::$app->homeUrl,
                        'linkOptions' => array(
                            'target' => '_blank',
                            'data-toggle' => 'tooltip',
                            'data-placement' => 'bottom',
                            'data-title' => Yii::t('app', 'Go to website')
                        ),
                    ],
                    [
                        'label' => '<span class="hidden-sm hidden-xs">' . Yii::$app->user->identity->username . '</span><span class="hidden-md hidden-lg"><i class="ti-user"></i></span>',
                        'url' => '#',
                        'active' => in_array($method, array('update-profile', 'update-password')),
                        'items' => array(
                            array(
                                'label' => Yii::t('app', 'Editing profile'),
                                'url' => '/admin/user/update-profile',
                                'active' => $method === 'update-profile',
                            ),
                            array(
                                'label' => Yii::t('app', 'Changing password'),
                                'url' => '/admin/user/update-password',
                                'active' => $method === 'update-password',
                            ),
                            '<li class="divider"></li>',
                            '<li>'
                            . Html::beginForm('/user/logout', 'post', ['class' => 'logout'])
                            . Html::submitButton(
                                'Выйти',
                                ['class' => 'btn btn-link']
                            )
                            . Html::endForm()
                            . '</li>',
                        ),
                    ],
                ],
            ]);
            ?>
        </div>
    </nav>
</div>

backend/views/layouts/_sidebar.php
<?php
        use yii\widgets\Menu;
	$controllerId = Yii::$app->controller->id;
        $method = Yii::$app->controller->action->id;
?>



<div class="site-sidebar custom-scroll custom-scroll-dark">
    <?php
    echo Menu::widget([
        'options' => ['class' => 'sidebar-menu'],
        'submenuTemplate' => '<ul>{items}</ul>'."\n",
        'items' => [
            ['label' => Yii::t('app', 'Contacts'), 'url' => '/admin/contact', 'active' => ($controllerId == 'contact')],
            ['label' => Yii::t('app', 'Модули'),
                'items' => [
                    ['label' => Yii::t('app', 'Slides'), 'url' => '/admin/slide', 'active' => ($controllerId == 'slide')],
                    ['label' => Yii::t('app', 'Advantage'), 'url' => '/admin/advantage', 'active' => ($controllerId == 'advantage')],
                    ['label' => Yii::t('app', 'Services'), 'url' => '/admin/service', 'active' => ($controllerId == 'service')],
                ],
                'options' => ['class'=>'with-sub'],
                'template' => '<span>{label}</span>',
            ],
			['label' => Yii::t('app', 'Pages'), 'url' => '/admin/page', 'active' => ($controllerId == 'page')],
            ['label' => Yii::t('app', 'Menu'), 'url' => '/admin/menu', 'active' => ($controllerId == 'menu')],
        ],
    ]);
    ?>

</div>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use app\assets\AdminAsset;

AdminAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <?=$this->registerLinkTag(['rel' => 'icon', 'type' => 'image/ico', 'href' => Url::to(['/images/favicon-backend.ico'])]); ?>
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) . ' - ' . Yii::t('app', 'Admin panel'); ?></title>
    <?php $this->head() ?>
    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="fixed-sidebar">
<?php $this->beginBody() ?>

<div class="wrapper">
    
    <!-- Mobile menu overlay -->
    <div class="mobile-menu-overlay"></div>

    <!-- Sidebar -->
    <?php echo $this->render('/layouts/_sidebar'); ?>

    <div class="site-content">

        <!-- Header -->
        <?php echo $this->render('/layouts/_header'); ?>
        <div class="breadcrumb-area">
            <div class="container-fluid">
                <?= Breadcrumbs::widget([
                    'homeLink' => [
                        'label' => 'Административная панель',
                        'url' => '/admin/index',
                    ],
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    //'links' => $this->params['breadcrumbs'],
                ]); ?>
            </div>
        </div>
            
        <!-- Content -->
        <div class="container-fluid m-t-20">
            
            <?= Alert::widget(); ?>
            
            <?= $content; ?>
            
        </div>
            
    </div>
</div>
    
<!-- Footer -->
<footer>
    <div class="container-fluid">
        &copy; <?php echo date('Y'); ?> &laquo;<?php echo Yii::$app->name; ?>&raquo;
    </div>
</footer>
    
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>